const fs = require('fs').promises;
const path = require('path');
const { exec } = require('child_process');
const util = require('util');
const execPromise = util.promisify(exec);

class NginxService {
  constructor() {
    this.nginxConfigDir = process.env.NGINX_CONFIG_DIR || path.join(__dirname, '../../nginx/vhosts');
  }

  generateVhostConfig(domainName, familyId, targetPort = 5000) {
    const cleanDomain = domainName.replace(/^(https?:\/\/)?(www\.)?/, '').trim().toLowerCase();
    
    return `# Auto-generated by FamilyHub Dynamic Reverse Proxy Service
# Family Tenant ID: ${familyId}
# Domain: ${cleanDomain}

server {
    listen 80;
    listen [::]:80;
    server_name ${cleanDomain} www.${cleanDomain};

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${cleanDomain} www.${cleanDomain};

    ssl_certificate /etc/letsencrypt/live/${cleanDomain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${cleanDomain}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Dynamic Tenant Header Routing
    proxy_set_header X-Tenant-Family-ID "${familyId}";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location / {
        proxy_pass http://127.0.0.1:${targetPort};
    }
}
`;
  }

  async applyTenantMapping(domainName, familyId) {
    const cleanDomain = domainName.replace(/^(https?:\/\/)?(www\.)?/, '').trim().toLowerCase();
    const configContent = this.generateVhostConfig(cleanDomain, familyId);

    try {
      await fs.mkdir(this.nginxConfigDir, { recursive: true });
      const targetFilePath = path.join(this.nginxConfigDir, `${cleanDomain}.conf`);
      await fs.writeFile(targetFilePath, configContent, 'utf8');

      console.log(`[Nginx Service] Written virtual host configuration to ${targetFilePath}`);

      // Perform Nginx test and reload if running in Linux production environment
      if (process.platform === 'linux') {
        await execPromise('sudo nginx -t');
        await execPromise('sudo nginx -s reload');
        console.log(`[Nginx Service] Nginx configuration reloaded successfully.`);
      }

      return {
        success: true,
        domainName: cleanDomain,
        familyId,
        configPath: targetFilePath
      };
    } catch (err) {
      console.warn(`[Nginx Service] Configuration written, reload skipped on non-linux OS or permission restricted environment: ${err.message}`);
      return {
        success: true,
        domainName: cleanDomain,
        familyId,
        warning: err.message
      };
    }
  }
}

module.exports = new NginxService();
