const fs = require('fs').promises;
const fsSync = require('fs');
const path = require('path');
const { exec } = require('child_process');
const util = require('util');
const execPromise = util.promisify(exec);

class NginxService {
  constructor() {
    this.isLinux = process.platform === 'linux';
    this.nginxAvailableDir = '/etc/nginx/sites-available';
    this.nginxEnabledDir = '/etc/nginx/sites-enabled';
    
    // For local Windows development testing fallback (avoid crashing if not in prod)
    if (!this.isLinux) {
      this.nginxAvailableDir = path.join(__dirname, '../../nginx/sites-available');
      this.nginxEnabledDir = path.join(__dirname, '../../nginx/sites-enabled');
      fsSync.mkdirSync(this.nginxAvailableDir, { recursive: true });
      fsSync.mkdirSync(this.nginxEnabledDir, { recursive: true });
    }
    
    console.log(`[Startup] NginxService Initialized.`);
    console.log(`[Startup] Nginx Available Dir: ${this.nginxAvailableDir}`);
    console.log(`[Startup] Nginx Enabled Dir: ${this.nginxEnabledDir}`);
  }

  generateVhostConfig(domainName, familyId, targetPort = 5000, sslReady = false) {
    const cleanDomain = domainName.replace(/^(https?:\/\/)?(www\.)?/, '').trim().toLowerCase();
    
    let config = `# Auto-generated by FamilyHub Dynamic Reverse Proxy Service
# Family Tenant ID: ${familyId}
# Domain: ${cleanDomain}

server {
    listen 80;
    listen [::]:80;
    server_name ${cleanDomain} www.${cleanDomain};

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        ${sslReady ? 'return 301 https://$host$request_uri;' : `proxy_pass http://127.0.0.1:${targetPort};\n        proxy_set_header Host $host;`}
    }
}
`;

    if (sslReady) {
      config += `
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${cleanDomain} www.${cleanDomain};

    ssl_certificate /etc/letsencrypt/live/${cleanDomain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${cleanDomain}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Dynamic Tenant Header Routing
    proxy_set_header X-Tenant-Family-ID "${familyId}";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location / {
        proxy_pass http://127.0.0.1:${targetPort};
    }
}
`;
    }

    return config;
  }

  async applyTenantMapping(domainName, familyId, sslReady = false) {
    const cleanDomain = domainName.replace(/^(https?:\/\/)?(www\.)?/, '').trim().toLowerCase();
    const configContent = this.generateVhostConfig(cleanDomain, familyId, 5000, sslReady);

    const availablePath = path.join(this.nginxAvailableDir, `${cleanDomain}.conf`);
    const enabledPath = path.join(this.nginxEnabledDir, `${cleanDomain}.conf`);

    try {
      if (this.isLinux) {
        // Write to sites-available using sudo to ensure permissions
        const tempPath = `/tmp/${cleanDomain}.conf`;
        await fs.writeFile(tempPath, configContent, 'utf8');
        await execPromise(`sudo mv ${tempPath} ${availablePath}`);
        await execPromise(`sudo chown root:root ${availablePath}`);
        
        // Create symlink
        await execPromise(`sudo ln -sf ${availablePath} ${enabledPath}`);
        console.log(`[Nginx Service] Config written and symlinked for ${cleanDomain}`);

        // Test configuration
        await execPromise('sudo nginx -t');
        console.log(`[Nginx Service] Nginx configuration passed validation.`);

        // Reload Nginx
        await execPromise('sudo systemctl reload nginx');
        console.log(`[Nginx Service] Nginx configuration reloaded successfully.`);
      } else {
        // Local fallback
        await fs.writeFile(availablePath, configContent, 'utf8');
        await fs.writeFile(enabledPath, configContent, 'utf8');
      }

      return {
        success: true,
        domainName: cleanDomain,
        familyId,
        configPath: availablePath
      };
    } catch (err) {
      console.error(`[Nginx Service] Failed to apply tenant mapping for ${cleanDomain}:`, err.message);
      throw new Error(`Nginx mapping failed: ${err.message}`);
    }
  }

  async rollbackTenantMapping(domainName) {
    const cleanDomain = domainName.replace(/^(https?:\/\/)?(www\.)?/, '').trim().toLowerCase();
    const availablePath = path.join(this.nginxAvailableDir, `${cleanDomain}.conf`);
    const enabledPath = path.join(this.nginxEnabledDir, `${cleanDomain}.conf`);

    try {
      if (this.isLinux) {
        console.log(`[Nginx Service] Rolling back config for ${cleanDomain}`);
        await execPromise(`sudo rm -f ${enabledPath}`);
        await execPromise(`sudo rm -f ${availablePath}`);
        
        try {
          await execPromise('sudo nginx -t');
          await execPromise('sudo systemctl reload nginx');
        } catch (reloadErr) {
          console.warn(`[Nginx Service] Rollback completed but Nginx reload failed: ${reloadErr.message}`);
        }
      } else {
        await fs.unlink(availablePath).catch(() => {});
        await fs.unlink(enabledPath).catch(() => {});
      }
      return true;
    } catch (err) {
      console.error(`[Nginx Service] Rollback failed for ${cleanDomain}:`, err.message);
      return false;
    }
  }
}

module.exports = new NginxService();
